### ISSUE TITLE
Efecto oscuro en las cards

### ISSUE THREAD

**Issue by GandresCoello18** [rcarlosalba/socialMediaDashboard#1]
`
let lightbg = document.querySelector(".lightbg"); // querySelector = obtiene 1 solo elemento
    let lightbgbox = document.querySelectorAll(".lightbgbox"); // querySelectorAll = obtiene todo los elementos con la clase ".lightbgbox" y lo mustra en un Array

function darkMode(){
      lightbg.classList.toggle('darkbg')
      lightbgsmall.classList.toggle('darkbgsmall')  
      //lightbgbox.classList.add('darkbgbox')

      console.log(lightbgbox); // muestra todos los elementos con esa clase.
      // para marcar las tarjetas oscuro, necesitamos acceder al elemento con su pocision [i] respectivo, ya que un array comienza de 0
      
      for(i=0; i<lightbgbox.length; i++){
        lightbgbox[i].classList.toggle('darkbgbox');
      }

    }
`

**Comment by rcarlosalba** [comment]
Gracias Andres!
Ya esta resuelto! Gracias por tu ayuda!
